### ISSUE TITLE
Inconsistent if block names

### ISSUE THREAD

**Issue by Exxabite** [Exxabite/TMC#11]
Block names should follow the pattern:

```
if0:
    if0:
    if1:
    if1_else:
if1:
    if0:
if2:
```

And be compiled to:
```
if0
if0.if0
if0.if1
if0.if1_else
if1
if1.if0
if2
```
